a.out:  ConsecutiveHeads.o random.o 
	g++ ConsecutiveHeads.o random.o

ConsecutiveHeads.o:  ConsecutiveHeads.cpp random.h
	g++ -c ConsecutiveHeads.cpp

random.o:  random.cpp random.h
	g++ -c random.cpp